# Generated by Django 4.0.3 on 2022-03-22 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='choice',
            table='choices',
        ),
        migrations.AlterModelTable(
            name='question',
            table='questions',
        ),
    ]
